<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.*" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\SharedProjects\HITS.Blazor.PushButton\HITS.Blazor.PushButton.csproj" />
  </ItemGroup>
</Project>